---
title: "Bison Dataset Cleaning"
format: html
author: "Jaslyn Miura"
---

```{r, message=FALSE}
# Load necessary libraries.
library(tidyverse)
library(here)
library(lubridate)
```

```{r, message=FALSE}
# Load raw data.
df_1 <- read_csv(here::here("data", "konza_prairie_bison", "CBH011.csv"))
df_2 <- read_csv(here::here("data", "konza_prairie_bison", "CBH012.csv"))
df_3 <- read_csv(here::here("data", "konza_prairie_bison", "CBH013.csv"))
```

```{r}
# Correct data types of df_1.
df1_cleaned <- df_1 %>% 
  mutate(RecType = as.integer(RecType)) %>% 
  mutate(RecYear = as.integer(RecYear)) %>% 
  mutate(BirthYear = as.integer(BirthYear)) %>% 
  mutate(NumofFemale = as.integer(NumofFemale)) %>% 
  mutate(NumofMale = as.integer(NumofMale))
```

```{r}
# Correct data types of df_2.
df2_cleaned <- df_2 %>% 
  filter(AnimalWeight != ".") %>% 
  mutate(RecType = as.integer(RecType)) %>% 
  mutate(RecYear = as.integer(RecYear)) %>% 
  mutate(RecMonth = as.integer(RecMonth)) %>% 
  mutate(RecDay = as.integer(RecDay)) %>% 
  mutate(AnimalWeight = as.integer(AnimalWeight)) %>% 
  mutate(AnimalYOB = as.integer(AnimalYOB))
summary(df2_cleaned)
```

```{r}
# Correct data types of df_3.
df3_cleaned <- df_3 %>% 
  mutate(RecType = as.integer(RecType)) %>% 
  mutate(RecYear = as.integer(RecYear))
```

```{r}
# Write the cleaned data file.
write_csv(df1_cleaned, "data/df1_cleaned.csv")
write_csv(df2_cleaned, "data/df2_cleaned.csv")
write_csv(df3_cleaned, "data/df3_cleaned.csv")
```

